name: Lint


on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - '.clj-kondo/config.edn'
      - 'src/core/**/*.clj'
      - 'src/core/**/*.cljs'
      - 'src/core/**/*.cljc'
    branches:
      - master
  pull_request:
    branches:
      - master


env:
  clj-kondo-version: '2022.10.05'


jobs:
  clj-kondo:
    name: Lint with clj-kondo
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: DeLaGuardo/clojure-lint-action@f712330e03eec4daa36da7045213190083aca4dd
      #   with:
      #     clj-kondo-args: --lint src # --config .clj-kondo/config.edn
      #     # check-name is optional
      #     check-name: This is a report name
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: ${{ env.clj-kondo-version }}
      - name: Lint
        run: |
          clj-kondo --lint src/core
          # --config .clj-kondo/config.edn
      - name: Discord action job digest notification
        uses: sarisia/actions-status-discord@v1
        if: always() # Pick up events even if the job fails or is canceled.
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
